name = "graphstruc"
version = "0.1.0"
author = "Ned Thaddeus Taylor"
maintainer = "n.t.taylor@exeter.ac.uk"
description = "A Fortran library for graph structures"

[preprocess]
[preprocess.cpp]
suffixes = ["F90", "f90"]

[library]
source-dir="src"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
